name: Backend Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install dependencies
        run: |
            cd backend
            pip install -r requirements.txt
      - name: Run Tests
        run: |
            # cd backend
            # pytest tests/unit 
            echo "Skipping unit tests for now"

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest httpx
      - name: Run Tests
        run: |
          cd backend
          # Skipping E2E tests in CI as they require local K8s
          # pytest tests/unit
          echo "Unit tests placeholder"
