"""Add system settings, semesters and teacher profile fields

Revision ID: 705f1561b779
Revises: f48da294fdf0
Create Date: 2025-12-31 00:07:07.662469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705f1561b779'
down_revision: Union[str, None] = 'f48da294fdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_index(op.f('ix_semesters_name'), 'semesters', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('portal_title', sa.String(), nullable=True),
    sa.Column('env_type', sa.String(), nullable=True),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('help_url', sa.String(), nullable=True),
    sa.Column('footer_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.add_column('teachers', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('department', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'department')
    op.drop_column('teachers', 'full_name')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_semesters_name'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    # ### end Alembic commands ###
