"""Add Teacher role, Student teacher_id, Registry

Revision ID: f48da294fdf0
Revises: bc2e40a752f0
Create Date: 2025-12-30 10:54:41.271323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48da294fdf0'
down_revision: Union[str, None] = 'bc2e40a752f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual fix: Create enum type first for Postgres
    # Using raw SQL to be safe against existing type (idempotent-ish)
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN CREATE TYPE userrole AS ENUM ('admin', 'teacher'); END IF; END $$;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registries_id'), 'registries', ['id'], unique=False)
    op.create_index(op.f('ix_registries_name'), 'registries', ['name'], unique=False)
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'teachers', ['teacher_id'], ['id'])
    op.add_column('teachers', sa.Column('role', sa.Enum('admin', 'teacher', name='userrole'), server_default='teacher', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'role')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'teacher_id')
    op.drop_index(op.f('ix_registries_name'), table_name='registries')
    op.drop_index(op.f('ix_registries_id'), table_name='registries')
    op.drop_table('registries')
    
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
