"""Add student authentication fields

Revision ID: d5039572a91c
Revises: 705f1561b779
Create Date: 2025-12-31 00:15:02.804957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5039572a91c'
down_revision: Union[str, None] = '705f1561b779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('students', sa.Column('role', sa.String(), server_default='student', nullable=False))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'role')
    op.drop_column('students', 'password_hash')
    # ### end Alembic commands ###
