"""add build config and build tables

Revision ID: 0eddd469af3a
Revises: 70959d10c5ef
Create Date: 2026-01-02 10:40:11.475438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eddd469af3a'
down_revision: Union[str, None] = '70959d10c5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_configs',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('dockerfile_path', sa.String(), nullable=False),
    sa.Column('context_path', sa.String(), nullable=False),
    sa.Column('registry_id', sa.String(), nullable=True),
    sa.Column('image_repo', sa.String(), nullable=True),
    sa.Column('tag_strategy', sa.String(), nullable=False),
    sa.Column('auto_build', sa.Boolean(), nullable=False),
    sa.Column('auto_deploy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_build_configs_student_id'), 'build_configs', ['student_id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('image_tag', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'error', 'cancelled', name='build_status_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('log_object_key', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_id'), 'builds', ['id'], unique=False)
    op.create_index(op.f('ix_builds_student_id'), 'builds', ['student_id'], unique=False)
    op.add_column('deployments', sa.Column('build_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deployments', 'builds', ['build_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'build_id')
    op.drop_index(op.f('ix_builds_student_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_build_configs_student_id'), table_name='build_configs')
    op.drop_table('build_configs')
    # ### end Alembic commands ###
