"""add build settings to system_settings

Revision ID: ce409d0a915d
Revises: 0eddd469af3a
Create Date: 2026-01-02 11:10:51.757384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce409d0a915d'
down_revision: Union[str, None] = '0eddd469af3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('build_namespace', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('default_registry_id', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('default_image_repo_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'default_image_repo_template')
    op.drop_column('system_settings', 'default_registry_id')
    op.drop_column('system_settings', 'build_namespace')
    # ### end Alembic commands ###
